services:
  zero2prod:
    image: zero2prod
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - APP_DATABASE__USERNAME=${DB_USER}
      - APP_DATABASE__PASSWORD=${DB_PASSWORD}
      - APP_DATABASE__NAME=${DB_NAME}
      - APP_DATABASE__HOST=${DB_HOST}
      - APP_DATABASE__PORT=${DB_PORT}
    # depends_on:
    #   - postgres_db

  ## TODO: Build postgres Dockerfile
  # postgres_db:
  #   image: docker.io/library/postgres:latest
  #   env_file: .env
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   ports:
  #     - "5432:5432"